language: go

services:
  - docker

go:
  - 1.13.x

git:
  depth: 1

notifications:
  email: false

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make build-image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make push-image