{{- if and .Values.podDisruptionBudget (gt (.Values.replicas | int) 1) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "dockerconfig-controller.fullname" . }}
  labels:
    app: {{ template "dockerconfig-controller.name" . }}
    chart: {{ template "dockerconfig-controller.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "dockerconfig-controller.name" . }}
      release: {{ .Release.Name | quote }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}