apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dockerconfig-controller.fullname" . }}
  labels:
    app: {{ template "dockerconfig-controller.name" . }}
    chart: {{ template "dockerconfig-controller.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
   config.yaml: {{ .Values.config | toJson | b64enc }}
type: Opaque